import "std/io.script"
import "std/types.script"

void PrintFibonacciSequence(int amount)
{
    int x;
    int y = 1;
    int z;
    
    for (int i = 0; i < amount; i++)
    {
        WriteLine(ToString(x));
        string padding1;
        int test = 0;

        z = x + y;
        x = y;
        y = z;
    }
    return;
}

void main()
{
    WriteLine("test");

    int padding;
    int padding1;

    int base = 2342;
    memory test = &base;
    int super = *test;

    WriteLine(IntToString(super));

    PrintFibonacciSequence(ToInt(GetLine()));
}