import "std/io.script"
import "std/types.script"
import "std/string.script"

int Factorial(int value)
{
    int ret = 0;
    while (value != 0)
    {
        ret = ret * value;
        value = value - 1;
    }
    return ret;
}

void PrintFibonacciSequence(int amount)
{
    int x;
    int y = 1;
    int z;

    for (int i = 0; i < amount; i += 1)
    {
        WriteLine(ToString(x));

        z = x + y;
        x = y;
        y = z;
    }
}

void main()
{
    string range = IndexStringRange("this is a long string", 1, 6); #this is commentary
    WriteLine(range);
}