import "std/io.script"
import "std/types.script"

void PrintFibonacciSequence(int amount)
{
    int x;
    int y = 1;
    int z;
    
    for (int i = 0; i < amount; i++)
    {
        WriteLine(ToString(x));
        string padding1;
        int test = 0;

        z = x + y;
        x = y;
        y = z;
    }
}

void PrintHelloWorld(memory text)
{
    WriteLine(*text);
}

void main()
{
    string test = "hello world!";
    memory ptr = &test;
    PrintHelloWorld(ptr);
}